### ISSUE TITLE
Add a Meditate work type for Vanilla Psycasts Expanded

### ISSUE THREAD

**Issue by jefferyharrell** [CaptainArbitrary/ManyJobs#39]
From AlotMaster on Steam:

> any way you could add Meditate for VPE?

https://steamcommunity.com/workshop/filedetails/?id=2842502659

**Comment by LionelColaso** [comment]
you can check this for reference
https://steamcommunity.com/sharedfiles/filedetails/?id=2324532667
https://github.com/maarxx/MeditateAsWorkType

**Comment by jefferyharrell** [comment]
Thanks, amigo. Much obliged.

**Comment by jefferyharrell** [comment]
Closing this as wontfix. Vanilla Psycasts Expanded does not seem to add any WorkTypeDefs or WorkGiverDefs, so there's nothing for Many Jobs to do. Since Meditate As Work Type exists and works with Many Jobs (I've tested it), I'm going to call that a solution.
